### PR TITLE
Fixed game by replacing local with lib in the import of asciilib in player and enemies object

### PR DESCRIPTION
**Pull request by Pixdigit**

### CODE REVIEW

**Comment by miezebieze** [comment]
thank you; i never would have hoped to see h in action again
 :3 <3

**Comment by Pixdigit** [comment]
No problem ;)
And have you read my comment on your pull request?

**Comment by miezebieze** [comment]
you were totally objective about my code and i could not see any harshness in your words

**Comment by Pixdigit** [comment]
@miezebieze Ok ((btw if you want to help me making my game you can always join as an official team member ;))

**Pull request merged**
